//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountID { get; set; }
        public string Phone { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> TheType { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> AUserNum { get; set; }
        public Nullable<System.DateTime> AccEndDate { get; set; }
        public Nullable<System.DateTime> VIPEndDate { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<int> VUserCount { get; set; }
        public Nullable<int> MaxVUserCount { get; set; }
        public Nullable<System.DateTime> RegistDate { get; set; }
    }
}
