//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarCall
    {
        public int CarCallID { get; set; }
        public string CarNo { get; set; }
        public string CarName { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public Nullable<int> ISRecWXMessage { get; set; }
        public Nullable<int> ISShowPhone { get; set; }
        public Nullable<int> ISHidePhone { get; set; }
        public string QrCodeURL { get; set; }
        public string WXOpenID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Code { get; set; }
        public string Memo { get; set; }
    }
}
