//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFJControl
    {
        public int CFJControlID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> DelayTime { get; set; }
        public Nullable<int> IsRun { get; set; }
        public Nullable<System.DateTime> ExeTime { get; set; }
        public string MachineCode { get; set; }
        public string Command { get; set; }
        public string WXOpenID { get; set; }
        public string CFJQrCode { get; set; }
        public string CZIP { get; set; }
        public string GroupCode { get; set; }
        public string Param { get; set; }
        public Nullable<int> AddMemberID { get; set; }
        public string Func { get; set; }
    }
}
