//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFJMemberType
    {
        public int CFJMemberTypeID { get; set; }
        public Nullable<int> MemberType { get; set; }
        public Nullable<int> DelayTime { get; set; }
        public Nullable<int> DayCount { get; set; }
        public Nullable<int> YearCount { get; set; }
        public string Name { get; set; }
        public Nullable<int> MonthCount { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public string Memo { get; set; }
        public Nullable<int> IsPublic { get; set; }
    }
}
