//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public int ChannelID { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public string SMSTag { get; set; }
        public string ImgURL { get; set; }
        public string Title { get; set; }
        public string Intro { get; set; }
        public Nullable<int> IsKaMi { get; set; }
    }
}
