//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int GoodID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<int> TotalNum { get; set; }
        public Nullable<int> BuyCount { get; set; }
        public string ImgUrl { get; set; }
        public string Intro { get; set; }
        public string Tags { get; set; }
        public string Desc { get; set; }
        public Nullable<int> Status { get; set; }
        public string BannerImgUrl { get; set; }
        public Nullable<int> IsShowBanner { get; set; }
        public Nullable<int> BannerOrder { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> GoodOrder { get; set; }
        public Nullable<int> AddMemberID { get; set; }
        public Nullable<decimal> OrgPayment { get; set; }
        public string Memo { get; set; }
        public Nullable<int> GoodType { get; set; }
        public string Param { get; set; }
        public Nullable<int> NeedTiLiNum { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public Nullable<decimal> ExpressFee { get; set; }
        public Nullable<int> JoinPeopleNum { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<decimal> Payment2 { get; set; }
        public Nullable<decimal> DayPrice { get; set; }
        public Nullable<decimal> SecurityPrice { get; set; }
        public string WuLiuType { get; set; }
        public Nullable<int> RefMemberID { get; set; }
        public Nullable<int> SellType { get; set; }
        public Nullable<int> XiaoQuID { get; set; }
        public string Call { get; set; }
        public string ImgList { get; set; }
        public string NiceName { get; set; }
        public string AddMemberHeadImgURL { get; set; }
    }
}
