//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodSort
    {
        public int GoodSortID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> Enabled { get; set; }
        public Nullable<int> GoodSortOrder { get; set; }
        public Nullable<int> ShowInIndex { get; set; }
        public string ShowName { get; set; }
        public Nullable<int> AddMemberID { get; set; }
    }
}
