//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guide
    {
        public int GuideID { get; set; }
        public string Name { get; set; }
        public string GuideNo { get; set; }
        public string Memo { get; set; }
        public Nullable<int> Status { get; set; }
        public string Skills { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<double> StartLevel { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Times { get; set; }
        public Nullable<int> BusyStatus { get; set; }
        public string HeadUrl { get; set; }
        public string VideoShowUrl { get; set; }
        public string SkillPoints { get; set; }
        public string PhoneNumber { get; set; }
        public string IDCard { get; set; }
        public string Intorduction { get; set; }
    }
}
