//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotterySellerRef
    {
        public int LotterySellerRefID { get; set; }
        public Nullable<int> LotteryID { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> OpeMemberID { get; set; }
    }
}
