//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public int MemberID { get; set; }
        public string Name { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string NiceName { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public Nullable<decimal> Balance_back { get; set; }
        public string WechatOpenid { get; set; }
        public string HeadImgUrl { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public Nullable<int> TheType { get; set; }
        public Nullable<int> IsGuanZhu { get; set; }
        public string Unionid { get; set; }
        public Nullable<int> UserLevel { get; set; }
        public Nullable<int> RefMemberID { get; set; }
        public Nullable<int> TiLiNum { get; set; }
        public Nullable<int> ISCFJUser { get; set; }
        public Nullable<int> CFJMemberTypeID { get; set; }
        public Nullable<int> CFJDayCount { get; set; }
        public Nullable<int> CFJYearCount { get; set; }
        public string Token { get; set; }
        public string Session_key { get; set; }
        public Nullable<int> XiaoQuID { get; set; }
        public string QuanIDs { get; set; }
        public string RenZhengUrl { get; set; }
        public Nullable<int> IsRenZhengPass { get; set; }
        public Nullable<int> RefSellerID { get; set; }
        public Nullable<int> IsAuthen { get; set; }
        public string RealName { get; set; }
        public string IDCard { get; set; }
        public Nullable<int> OwnerSellerID { get; set; }
    }
}
