//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCCLottery
    {
        public int NCCLotteryID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public string Intro { get; set; }
        public Nullable<int> TheOrder { get; set; }
        public string ImgUrl { get; set; }
        public string ImgUrl1 { get; set; }
        public string ImgUrl2 { get; set; }
        public string OrgImgUrl1 { get; set; }
        public string OrgImgUrl2 { get; set; }
        public string LotteryNo { get; set; }
        public Nullable<int> PrizeStatus { get; set; }
        public Nullable<System.DateTime> PrizeDate { get; set; }
        public Nullable<int> RefOrderID { get; set; }
        public Nullable<int> RefLotteryID { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<int> RefMemberID { get; set; }
        public Nullable<int> RefSellerID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> IsBeep { get; set; }
        public Nullable<System.DateTime> BeginOpenDate { get; set; }
        public Nullable<System.DateTime> EndOpenDate { get; set; }
        public Nullable<int> LotteryStatus { get; set; }
        public string PayBackReason { get; set; }
        public Nullable<int> IsNotifyBuyerPrizeInfo { get; set; }
        public Nullable<System.DateTime> NotifyBuyerPrizeInfoDate { get; set; }
    }
}
