//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCCOrders
    {
        public int OrderID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public string Memo { get; set; }
        public Nullable<decimal> NeedPay { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> PlayBeginDate { get; set; }
        public Nullable<System.DateTime> PlayEndDate { get; set; }
        public Nullable<int> BuyNum { get; set; }
        public Nullable<int> LotteryID { get; set; }
        public Nullable<int> Exchanged { get; set; }
        public Nullable<System.DateTime> ExchangeDate { get; set; }
        public Nullable<int> ExchangeMemberID { get; set; }
        public Nullable<int> SellerID { get; set; }
        public string MemberHeadUrl { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> NCCLotteryID { get; set; }
    }
}
