//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> GuideID { get; set; }
        public string MemberOpenid { get; set; }
        public Nullable<int> ServiceMinute { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public string Memo { get; set; }
        public string ShortUrl { get; set; }
        public Nullable<int> PayType { get; set; }
        public Nullable<decimal> NeedPay { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Property { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string GuideOpenid { get; set; }
    }
}
