//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public int SellerID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string SellerNo { get; set; }
        public Nullable<int> IsOnline { get; set; }
        public Nullable<int> TheOrder { get; set; }
        public Nullable<int> QueueNum { get; set; }
        public Nullable<int> Status { get; set; }
        public string VideoShowURL { get; set; }
        public string VideoPushURL { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<int> ManagerMemberID { get; set; }
    }
}
