//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShangJia
    {
        public int ShangJiaID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Call { get; set; }
        public string Desc { get; set; }
        public string ImgList { get; set; }
        public Nullable<int> NeedPayQr { get; set; }
        public string ManagerName { get; set; }
        public string ManagerCall { get; set; }
        public string QrCodeUrl { get; set; }
        public Nullable<int> ISPassed { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> AddMemberID { get; set; }
        public Nullable<int> XiaoQuID { get; set; }
        public string ImgUrl { get; set; }
    }
}
