//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZGGBBS
    {
        public int BBSID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string OpenID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ImgList { get; set; }
        public Nullable<int> QuanZiID { get; set; }
        public Nullable<int> XiaoQuID { get; set; }
    }
}
