//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ncc2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZGGUseControl
    {
        public int ZGGUseControlID { get; set; }
        public Nullable<int> NeighborUserID { get; set; }
        public Nullable<System.DateTime> PutInDate { get; set; }
        public Nullable<int> KDUserID { get; set; }
        public Nullable<System.DateTime> GetOutDate { get; set; }
        public Nullable<int> IsPrivate { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<decimal> Payed { get; set; }
        public Nullable<int> PayState { get; set; }
        public Nullable<int> ZGGPayID { get; set; }
        public Nullable<int> ZGGMachineID { get; set; }
        public string PassWord { get; set; }
    }
}
