//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKongZhongLiWu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public string Address1 { get; set; }
        public string ZipCode { get; set; }
        public string RecName { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
