//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKongZhongLiWu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public Good()
        {
            this.Orders = new HashSet<Order>();
            this.GoodSortMappings = new HashSet<GoodSortMapping>();
        }
    
        public int GoodID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<int> TotalNum { get; set; }
        public Nullable<int> BuyCount { get; set; }
        public string ImgUrl { get; set; }
        public string Intro { get; set; }
        public string Tags { get; set; }
        public string Desc { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<GoodSortMapping> GoodSortMappings { get; set; }
    }
}
