//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKongZhongLiWu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int MemberID { get; set; }
        public string Name { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string NiceName { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
