//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKongZhongLiWu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> GoodID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> BuyNum { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public string RecName { get; set; }
        public string RecAddress { get; set; }
        public string RecPhone { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public Nullable<int> TranceStatus { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public string Memo { get; set; }
        public string ShortUrl { get; set; }
        public string SayEtc { get; set; }
        public string ToName { get; set; }
        public string ToPhone { get; set; }
        public string ThePass { get; set; }
        public string DeliveryNo { get; set; }
        public string DeliveryCompany { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Good Good { get; set; }
    }
}
